# Generated by Django 5.0.3 on 2025-10-30 10:57

import base.models
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='project/images/visualization/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(base.models.DeepDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('safety', 'Safety'), ('amenities', 'Amenities'), ('parking', 'Parking'), ('fitness', 'Fitness'), ('pets', 'Pets'), ('firesafety', 'Fire Safety'), ('other', 'Other')], max_length=100, null=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('country', 'Country'), ('city', 'City'), ('district', 'District'), ('neighborhood', 'Neighborhood')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
                'unique_together': {('name', 'location_type')},
            },
            bases=(base.models.DeepDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property_name', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('construction', 'Under Construction'), ('completed', 'Completed'), ('planned', 'Planned')], default='construction', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex'), ('hotel_room', 'Hotel Room'), ('home_office', 'Home Office'), ('office', 'Office'), ('studio', 'Studio')], default='apartment', max_length=50)),
                ('bedrooms', models.CharField(choices=[('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedrooms'), ('3_bedroom', '3 Bedrooms'), ('4_bedroom', '4 Bedrooms'), ('5_plus_bedroom', '5+ Bedrooms'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('duplex', 'Duplex')], default='1_bedroom', max_length=50)),
                ('bathrooms', models.CharField(choices=[('1_bathroom', '1 Bathroom'), ('1.5_bathroom', '1.5 Bathrooms'), ('bathroom', '2 Bathrooms'), ('2.5_bathroom', '2.5 Bathrooms')], default='1_bathroom', max_length=50)),
                ('max_guests', models.CharField(blank=True, max_length=50, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('build_year', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex'), ('hotel_room', 'Hotel Room'), ('home_office', 'Home Office'), ('office', 'Office'), ('studio', 'Studio'), ('warehouse', 'Warehouse'), ('factory', 'Factory'), ('retail', 'Retail'), ('land', 'Land'), ('farm', 'Farm'), ('garage', 'Garage')], default='apartment', max_length=50)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('on_hold', 'On Hold'), ('needs_revision', 'Needs Revision'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amenities', models.ManyToManyField(blank=True, related_name='amenities', to='properties.amenity')),
                ('city', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'city'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_properties', to='properties.location')),
                ('country', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'country'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_properties', to='properties.location')),
                ('interior_images', models.ManyToManyField(related_name='interior_projects', to='properties.projectimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(base.models.DeepDeleteMixin, models.Model),
        ),
    ]
